[package]
name = "minimum-async-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
once_cell = "1.19.0"
pin-utils = "0.1"
waker-fn = "1"
log = "0.4.22"
env_logger = "0.11.3"